name: sync-remotes
on: [push, delete]

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.repository == 'crnvl96/cv-tex' && (github.event_name == 'push' || github.event_name == 'delete')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MIRROR_SYNC }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global core.sshCommand 'ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          git remote set-url codeberg ssh://git@codeberg.org/crnvl96/cv-tex.git || git remote add codeberg ssh://git@codeberg.org/crnvl96/cv-tex.git

      - name: Fetch all remotes
        run: git fetch --all

      - name: Push to Codeberg
        run: |
          git push codeberg --tags 'refs/remotes/origin/*:refs/heads/*'
